-- ============================================================
-- MIGRATION V7: MASTER HYGIENE STANDARDS
-- Master Acuan Standar Kebersihan Seluruh Cabang FCMS
-- Total: 104 parameter kebersihan dari 35 ruangan
-- ============================================================

CREATE TABLE IF NOT EXISTS master_hygiene_standards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  room_name TEXT NOT NULL,
  item_name TEXT NOT NULL,
  cleanliness_standard TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_hygiene_room ON master_hygiene_standards(room_name);

-- ============================================================
-- SEED DATA: 104 PARAMETER KEBERSIHAN (SOURCE OF TRUTH)
-- ============================================================
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lantai & Sudut Ruangan', 'Permukaan lantai ubin/vinyl, nat antar ubin, skirting/plint tepi, dan sudut-sudut mati ruangan.', 'Bebas debu kasat mata, tidak lengket, bebas noda kerak, nat ubin cerah tidak menghitam, dan sudut ruangan kering.');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Dinding, Partisi & Plint', 'Permukaan dinding cat, lis plint bawah, panel dinding (ACP), saklar, dan stop kontak listrik.', 'Bebas sarang laba-laba, bebas noda cipratan, bebas sidik jari berminyak, saklar bersih dan kering sempurna.');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Kaca, Cermin & Partisi Kaca', 'Kaca pintu utama, jendela, cermin wastafel toilet, kaca sekat loket, dan partisi ruangan.', 'Bening, transparan sempurna, bebas sidik jari, bebas flek percikan air (water spot), dan bebas serat kain.');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Sanitair & Area Basah Toilet', 'Kloset duduk/jongkok, wastafel keramik, jet shower, kran air, floor drain, dan dinding keramik toilet.', 'Higienis total, tidak berbau tidak sedap/pesing, keramik putih tanpa kerak kuning, kran stainless mengkilap kering.');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Plafon, Lampu & Kisi Ventilasi', 'Permukaan plafon gipsum, kap lampu penerangan, kisi-kisi exhaust fan, dan diffuser pendingin AC.', 'Plafon bersih rapi, bebas sarang laba-laba, kisi exhaust tidak ada lapisan serat debu tebal, lampu bersih terang.');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Mebel, Meja & Kursi Kerja/Pasien', 'Meja periksa/resepsionis, kursi tunggu pasien, kursi kerja tim, lemari arsip, rak display, dan laci.', 'Permukaan higienis terdesinfeksi, bebas debu rontokan, bebas noda tumpahan minuman/kopi, kolong meja bersih rapi.');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Peralatan Khusus & Medis Non-Steril', 'Casing eksterior Dental Unit (DU), dental chair, bodi unit ronsen X-ray, panel kompresor, dan troli tindakan.', 'Bodi luar bersih mulus, higienis, terbebas dari bercak percikan cairan klinik, debu di lekukan unit hilang tuntas.');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Wadah Sampah & Utilitas', 'Tempat sampah injak/medis, tong sulo luar gedung, dan wadah utilitas.', 'Wadah selalu terpasang kantong plastik sesuai kode warna dan bodi luar bersih mengkilap.');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Teras', 'Sudut/Pojok', 'Bebas noda, kerak lumut, puntung rokok, dan tumpukan kotoran kering');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Teras', 'Jalur Rolling Door', 'Bebas sampah daun, pasir, kerikil, dan endapan yang menghambat rel rolling door');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Teras', 'Rolling Door & ACP', 'Permukaan luar-dalam bersih dari debu tebal, sarang laba-laba, dan noda polusi jalanan');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Teras', 'Dinding, Lampu & Plafon', 'Dinding bebas noda cipratan, kap lampu bebas bangkai serangga, plafon tanpa sarang laba-laba');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Teras', 'Sulo & Tempat Sampah', 'Bersih bodi luar-dalam, tidak ada cairan tumpah lengket, tidak berbau busuk, tertutup rapat');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Teras', 'Keset Kaki (Entrance Mat)', 'Bebas pasir kasar, serat tidak basah becek, tidak berbau apek, posisi presisi di pintu masuk');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 1', 'Sudut/Pojok & Plint', 'Bebas daki sudut, debu halus, dan goresan noda sepatu pada plint bawah ruangan');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 1', 'Lantai Lobby', 'Mengkilap bersih, bebas minyak, tidak licin, nat ubin cerah, bebas remah debu kering/basah');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 1', 'Pintu Kaca & Partisi', 'Kaca bening jernih, bebas sidik jari (fingerprint), bebas bercak air, handle pintu steril bersih');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 1', 'Kursi & Meja Pasien', 'Bebas debu kasat mata, bebas noda tumpahan minuman, higienis, tertata sejajar rapi dan presisi');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 1', 'Dinding, Saklar & Stop Kontak', 'Dinding bebas noda coretan/benturan, saklar bersih mengkilap tanpa noda daki jari tangan');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 1', 'Plafon, Lampu & AC', 'Bebas sarang laba-laba, kisi filter AC bebas gumpalan debu putih/abu, kap lampu bersih mengkilap');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Receptionist', 'Meja & Front Counter', 'Permukaan meja bersih kinclong, rapi tanpa berkas berantakan, bebas debu & noda bekas pena/tinta');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Receptionist', 'Bawah Meja & Kabel', 'Kolong meja bersih bebas sampah remah/kertas, kabel tersusun rapi tidak berdebu tebal');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Receptionist', 'Lemari & Kursi Kerja', 'Lemari bebas debu, kursi tidak bernoda kusam, laci tertutup rapat dan permukaan luar higienis');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Snack Corner', 'Meja & Area Dispenser', 'Bebas tumpahan air/sirup, remah makanan, dispenser higienis tanpa lumut pada tatakan air (drip tray)');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Snack Corner', 'Lemari & Rak Snack', 'Rak snack tersusun rapi, bebas remah biskuit/makanan, permukaan rak bebas lapisan debu halus');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('DU 101', 'Lantai & Sudut Tindakan', 'Bersih steril, bebas percikan darah/cairan tindakan, tidak licin, tidak berbau obat menyengat');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('DU 101', 'Eksterior Dental Unit & Kursi', 'Casing unit bebas noda percikan, bodi mulus tanpa debu lipatan pipa, higienis total terdesinfeksi');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('DU 101', 'Wastafel & Kran Air', 'Wastafel porselen putih bebas kerak busa sabun, kran stainless mengkilap kering tanpa bercak air kusam');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('DU 101', 'Meja Dokter, Kursi & Lemari', 'Bebas debu kasat mata, tertata rapi, tidak ada debu di lipatan laci dan lemari gantung tindakan medis');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('DU 101', 'Tempat Tissue & Dispenser Handrub', 'Bodi dispenser bersih mengkilap tanpa daki, selalu terisi penuh, tidak ada tetesan menggumpal di lantai');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('DU 101', 'Dinding, Saklar, Kabel & Plint', 'Lis plint bebas noda sepatu, kabel dental rapi terbungkus spiral pelindung, saklar bersih higienis steril');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('DU 101', 'Plafon, Lampu, AC & CCTV', 'Plafon bebas sarang laba-laba, kisi AC bebas debu, cover CCTV mengkilap jernih tanpa lapisan kotoran');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ronsen', 'Lantai & Sudut Ruangan', 'Lantai bersih bebas debu radiologi, kering sempurna, bebas noda hitam bekas gesekan sepatu/roda mesin');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ronsen', 'Eksterior Mesin X-Ray & Apron', 'Bodi luar mesin X-ray bersih bebas debu dan sidik jari, apron timbal digantung rapi tanpa lekukan kotor');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ronsen', 'Meja Kerja, Kursi & Kabel', 'Meja komputer operator ronsen bebas debu, kabel unit tertata rapi dalam ducting tidak terurai kotor');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ronsen', 'Dinding, Pintu, AC & Plint', 'Pintu geser timbal bersih dari sidik jari, kisi exhaust/AC bebas debu, plint bawah rapi bebas noda');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Toilet 1', 'Kloset & Tutup Kloset', 'Bebas noda kerak kuning, bibir kloset luar dalam putih steril, tidak ada aroma pesing atau bau busuk');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Toilet 1', 'Wastafel, Cermin & Kran', 'Cermin bening tanpa cipratan air, keramik wastafel putih bersih, kran stainless mengkilap tanpa kerak air');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Toilet 1', 'Jet Shower & Floor Drain', 'Jet shower bebas lumut/kerak kapur, floor drain bersih dari rambut/kotoran, aliran air lancar tanpa sumbatan');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Toilet 1', 'Dinding, Lantai Keramik & Pintu', 'Lantai keramik bersih dan kesat tidak licin, dinding bebas noda sabun, handle pintu higienis bebas kuman');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Toilet 1', 'Tempat Tissue & Aroma Ruang', 'Tempat tisu terisi penuh dan kering, aroma toilet segar wangi tidak apek, tempat sampah tertutup rapat');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Toilet 1', 'Exhaust Fan & Plafon', 'Kisi exhaust fan bebas debu hitam menggumpal, plafon toilet bebas noda cipratan uap atau jamur lembap');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Janitor', 'Rak Alat & Botol Chemical', 'Peralatan & botol chemical tertata rapi berlabel, mop kain tergantung terbalik, rak simpan bersih dan kering');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Janitor', 'Slop Sink & Kran Air', 'Bak slop sink bersih bebas kerak kotoran/lumut, kran air stainless mengkilap kering, saluran pembuangan lancar tanpa endapan');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Janitor', 'Lantai & Floor Drain', 'Lantai bersih kesat bebas genangan air, saringan floor drain bebas kotoran rambut/serat pel, ruangan tidak berbau apek');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Limbah', 'Penataan Wadah & Plastik B3', 'Wadah sampah medis (kuning) dan domestik (hitam) tertutup rapat, berlabel jelas, tidak over capacity');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Limbah', 'Lantai, Dinding & Sudut', 'Lantai steril bebas ceceran cairan limbah, sudut bersih, dinding bebas noda cipratan kotoran sampah');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Limbah', 'Aroma & Exhaust Fan', 'Sirkulasi udara lancar, exhaust hidup aktif 24 jam, ruangan tidak tercium bau menyengat keluar selasar');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Steril', 'Lantai & Sudut Steril', 'Lantai steril higienis, bebas kontaminan partikel debu, sudut-sudut mati bersih mengkilap tanpa noda');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Steril', 'Wastafel Pencucian Alat & Kran', 'Bak wastafel bebas kerak karat/darah, kran air kencang mengkilap, sekeliling wastafel kering tuntas');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Steril', 'Lemari Gantung, Meja & Mebel', 'Meja packing instrumen bersih steril bebas partikel debu, daun pintu lemari tertutup rapat tanpa debu lipatan');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Steril', 'Dinding, Pintu, Saklar & AC', 'Dinding bersih tanpa flek noda, handle pintu steril terdesinfeksi rutin, kisi AC dingin bersih bebas debu');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Area Tangga', 'Anak Tangga & Sudut Bordes', 'Setiap anak tangga bebas debu pasir, noda tetesan permen/cairan, sudut bordes bersih dan kering aman dilewati');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Area Tangga', 'Hand Railling (Pegangan Tangga)', 'Bebas debu, bebas noda keringat tangan, mengkilap bersih dan terdesinfeksi aman disentuh pasien/karyawan');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Area Tangga', 'Dinding, Lampu & Plafon Tangga', 'Dinding sepanjang tangga bebas noda gesekan barang/sepatu, kap lampu tangga terang benderang bebas sarang laba-laba');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 2', 'Area Bermain & Matras Anak', 'Matras evamats/karpet bersih bebas remah biskuit, bebas debu, higienis aman disentuh anak-anak balita');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 2', 'Bola Kolam & Mainan Anak', 'Bola mandi bola dan mainan plastik bebas debu liur kotor, disinfeksi higienis tidak lengket berbau kuman');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 2', 'Lantai, Kursi Pasien & Meja', 'Lantai mengkilap bersih, kursi tunggu tertata rapi, meja bebas noda tumpahan minuman atau remah makanan');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 2', 'Freezer Ice Cream', 'Bodi luar freezer bersih bebas debu dan sidik jari, kaca geser atas bening transparan tanpa bercak es beku kotor');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lobby 2', 'Dinding, Plafon & Dekorasi', 'Dekorasi hiasan dinding/plafon bebas debu halus menempel, kap lampu penerangan bersih menyala maksimal');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Playground', 'Tempat Bermain Anak', 'Lantai matras/evamats bersih bebas remah makanan, bebas debu, kering tidak licin, higienis dan aman untuk balita');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Playground', 'Mainan Anak', 'Mainan bersih bebas bekas liur, noda daki dan kuman, tidak lengket berbau apek, aman dimasukkan mulut anak');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Playground', 'Kolam Penampung Bola', 'Dasar dan dinding kolam bebas debu, remah makanan, rambut, dan sampah tersembunyi, bodi luar bersih mengkilap');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Playground', 'Bola Playground', 'Bola plastik higienis, bebas kotoran lengket, debu dan noda air liur, tidak berbau dan terdesinfeksi menyeluruh');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Playground', 'Dekorasi', 'Hiasan dinding, stiker mural, dan ornamen bermain bebas sarang laba-laba, debu menempel, dan noda coretan krayon/spidol');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Musholla', 'Karpet Shalat & Sajadah', 'Bebas debu partikel, tidak berbau apek, harum segar, serat karpet bersih, garis shaf terpasang lurus rapi');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Musholla', 'Peralatan Shalat (Mukena/Sarung)', 'Mukena, sarung, dan sajadah cadangan bersih harum, terlipat sangat rapi di dalam rak lemari khusus');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Musholla', 'Rak Sepatu & Sandal Wudhu', 'Rak sepatu bebas tanah/pasir, sandal wudhu tersusun rapi searah menghadap keluar di depan pintu musholla');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Tempat Wudhu', 'Kran Air & Dinding Keramik', 'Kran mengkilap bebas kerak sabun/lumut, dinding keramik tempat wudhu bersih kesat tanpa endapan daki air');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Tempat Wudhu', 'Floor Drain & Lantai Wudhu', 'Lantai tidak berlendir licin, bebas genangan air, saringan floor drain bebas rambut/lumut, tidak berbau apek');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Dokter', 'Meja Konsul, Kursi & Komputer', 'Meja dokter bersih higienis, bebas debu, keyboard/layar monitor terbebas dari debu dan noda bekas jari tangan');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Dokter', 'Lantai, Sudut & Pintu', 'Lantai bersih bebas kotoran remah, beraroma segar nyaman untuk konsultasi, gagang pintu higienis terdesinfeksi');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Team', 'Meja Makan/Diskusi & Kursi', 'Bebas remah makanan, bebas noda bekas tumpahan saus/minyak, higienis, kursi tertata rapi merapat ke meja');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Team', 'Wastafel Cuci Piring & Kran', 'Bak cuci piring bersih bebas tumpukan piring kotor berbau busuk, saringan sisa makanan kosong dan dibilas bersih');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Team', 'Lemari, Kulkas Luar & Penataan', 'Bodi luar kulkas dan lemari tim bersih dari sidik jari/tumpahan noda saus, barang logistik ruangan tersusun rapi');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Team', 'Loker Karyawan', 'Permukaan luar-dalam loker bersih bebas debu, tidak ada stiker usang/coretan, handle steril, dan bagian atas loker rapi tanpa tumpukan barang');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Gudang Farmasi & Bahan', 'Lantai, Sudut & Kolong Rak/Palet', 'Lantai bersih bebas debu, ceceran serbuk/cairan bahan, kolong rak tidak berdebu dan bebas hama/serangga');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Gudang Farmasi & Bahan', 'Rak Penyimpanan Bahan & Lemari Obat', 'Ambalan rak bersih bebas debu, botol dan wadah bahan tertata rapi, tidak ada tumpahan cairan obat/powder');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Gudang Farmasi & Bahan', 'Kulkas Farmasi (Chiller) & Termohigrometer', 'Bodi luar kulkas bersih mengkilap bebas debu dan sidik jari, karet pintu bersih tanpa jamur, display termometer jelas');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Gudang Farmasi & Bahan', 'Meja Kerja, Timbangan & Area Packing Bahan', 'Meja kerja bersih higienis bebas serbuk bahan medis, timbangan steril tanpa noda kimia, kursi rapi bebas debu');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Gudang Farmasi & Bahan', 'Dinding, Plafon, Kisi AC & Exhaust Fan', 'Bebas sarang laba-laba, kisi filter AC & exhaust bersih tanpa lapisan debu, dinding bebas noda lembap/jamur');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('RoofTop', 'Lantai, Saluran Air & Talang', 'Bebas sampah daun kering, genangan air hujan, lumut tebal, saluran pembuangan lancar tanpa sumbatan sampah atap');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('RoofTop', 'Tandon Air / Torrent Luar', 'Bodi luar torrent bersih bebas lumut hijau tebal dan endapan polusi debu luar ruangan, pipa kontrol bersih rapi');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Kompressor', 'Lantai & Penataan Ruang', 'Lantai bersih dari ceceran oli/minyak mesin, bebas debu industri tebal, barang sparepart tersusun aman dan rapi');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Ruang Kompressor', 'Exhaust Fan & Kisi Dinding', 'Kisi exhaust fan bebas gumpalan debu panas, sirkulasi udara mesin kompresor lancar dingin dan optimal');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lift', 'Dinding Stainless & Hand Railling', 'Dinding stainless steel bebas sidik jari (smudge), handrail steril mengkilap kering tanpa daki telapak tangan pengguna lift');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lift', 'Lantai Lift & Jalur Pintu (Sill)', 'Lantai bersih mengkilap tidak berdebu, celah celah rel pintu lift bebas pasir/kerikil pengganjal jalannya roda pintu lift');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lift', 'Tombol Panggilan, Indikator & Lampu', 'Tombol lift bersih steril terdesinfeksi higienis, cover lampu langit-langit lift terang benderang bebas lapisan debu');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Lift', 'Exhaust Fan & Kisi Langit-Langit', 'Kisi-kisi ventilasi exhaust lift bebas sarang laba-laba dan gumpalan debu pendingin sirkulasi udara lift pasien');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Area Genset', 'Lantai & Penataan Barang', 'Lantai bersih bebas ceceran oli/bahan bakar, tidak licin, bebas kain majun bekas berserakan, jalur evakuasi bebas hambatan');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Area Genset', 'Dinding & Plafon', 'Dinding bersih bebas jelaga knalpot/debu pekat, plafon bebas sarang laba-laba, kisi ventilasi udara bersih lancar');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Area Genset', 'Kebersihan Mesin Genset & Panel', 'Bodi luar genset bersih bebas lapisan debu tebal & rembesan oli, panel kontrol terbaca jelas dan kering, APAR genset bersih siap pakai');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Area Tangga Exit', 'Anak Tangga & Sudut Bordes', 'Bebas debu pasir, sampah, sudut bordes bersih dan kering tanpa genangan/noda hitam, jalur evakuasi tidak terhalang benda apapun');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Area Tangga Exit', 'Hand Railling (Pegangan Tangga)', 'Railing bersih mengkilap, bebas debu, bebas daki bekas keringat tangan, disinfeksi higienis dan aman dipegang');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Area Tangga Exit', 'Dinding, Lampu & Plafon', 'Dinding bebas goresan/noda kotor, lampu darurat menyala terang dan kap bebas sarang laba-laba, daun pintu exit bersih dan push-bar steril');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Taman', 'Tanaman, Rumput & Daun Kering', 'Bebas guguran daun kering, rumput terpangkas rapi, pot tanaman bebas lumut tebal, tidak ada sampah puntung rokok/plastik');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Taman', 'Jalur Setapak, Paving & Lampu Taman', 'Jalur setapak/paving bersih dari lumut licin dan tanah becek, tidak ada rumput liar tumbuh di sela paving/konblok, kap lampu taman bening menyala terang tanpa sarang serangga');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Pos Security', 'Meja Kerja, Kursi & Monitor CCTV', 'Meja pos bersih rapi bebas remah makanan/noda kopi, kursi bebas debu, layar monitor CCTV jernih bebas bekas sidik jari');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Pos Security', 'Lantai, Kaca Jendela & Pintu Pos', 'Lantai pos bersih mengkilap tidak licin, sudut pos bebas puntung rokok, kaca jendela pos bening transparan tanpa sidik jari atau debu');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Toilet Security', 'Kloset, Jet Shower & Kran Air', 'Kloset bersih bebas kerak kuning/pesing, jet shower dan kran air mengkilap bebas kerak air, tempat tisu dan sabun terisi rapi');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Toilet Security', 'Lantai, Dinding, Pintu & Floor Drain', 'Lantai keramik kesat tidak licin, dinding bebas daki sabun, floor drain lancar tanpa kotoran rambut, ruangan wangi segar tidak bau apek');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Halaman Parkir', 'Area Paving/Aspal & Marka Parkir', 'Bebas sampah plastik, daun kering, puntung rokok, ceceran oli kendaraan, garis marka parkir mobil/motor terlihat jelas dan bersih');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Halaman Parkir', 'Saluran Drainase, Grille Besi & Sudut Parkir', 'Tutup saluran air (grille besi) bebas endapan pasir dan sampah penyumbat, aliran got lancar tidak bau, sudut pagar bebas tumpukan kotoran');
INSERT INTO master_hygiene_standards (room_name, item_name, cleanliness_standard) VALUES ('Halaman Parkir', 'Rambu Parkir, Plang Masuk & Tempat Sampah Luar', 'Plang rambu parkir dan marka masuk bersih tegak lurus bebas debu jalanan, tempat sampah luar bersih tertutup rapat tanpa kantong plastik luber');
