UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '007. Bekasi') WHERE full_name = 'ACHMAD NURYAINI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '032. Cawang') WHERE full_name = 'ADAM JHORDY';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '016. Cibubur') WHERE full_name = 'ADE MUSTIKA REZDAFITRA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '026. Tangerang City') WHERE full_name = 'ADITYA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '054. Bogor Gunung Batu') WHERE full_name = 'ADITYA PRATAMA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'AGUNG SEPTIADI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '021. Kelapa Gading Boulevard') WHERE full_name = 'AGUS LEO SAGITA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '062. Summarecon Bekasi') WHERE full_name = 'AHMAD FARHAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '001. Pondok Bambu') WHERE full_name = 'AHMAD REZA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '004. Cipete') WHERE full_name = 'AHMAD SARIP HIDAYATULOH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '004. Cipete') WHERE full_name = 'AHMAD SUBHAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '009. Bintaro') WHERE full_name = 'ALDI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '033. Taman Mini') WHERE full_name = 'ALDO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '012. BSD') WHERE full_name = 'ALIF RIFQI ZAMARSYAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '003. Depok') WHERE full_name = 'AMBAR MUJITO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '023. Semarang') WHERE full_name = 'ANANTA SEPTRIANTO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '002. Kemang') WHERE full_name = 'ANDRE MAULANA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'ANGEL KASENDA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '002. Kemang') WHERE full_name = 'ANGGA ADITYA SAPUTRA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '016. Cibubur') WHERE full_name = 'ANGGI ADITYA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'ANJAS PRIANTO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '063. Pasar Minggu') WHERE full_name = 'ARDIANSYAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '004. Cipete') WHERE full_name = 'ARI SUYANTO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '022. Cikarang') WHERE full_name = 'ARIE JULIANTO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '013. Bandung Gatsu') WHERE full_name = 'ASEP ALIF';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '056. Citra Garden 2') WHERE full_name = 'AULIA AZKA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'AVIV AMAR';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '016. Cibubur') WHERE full_name = 'BAYU PRAKOSO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '059. Malang Suhat') WHERE full_name = 'BENY TEGOEH WIJAYA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '001. Pondok Bambu') WHERE full_name = 'CARLOS BENYGUUS SITOHANG';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '004. Cipete') WHERE full_name = 'CAYA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '016. Cibubur') WHERE full_name = 'CHANDRA AJI KURNIAWAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '013. Bandung Gatsu') WHERE full_name = 'DADAN NURJAMAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '031. Sawangan') WHERE full_name = 'DANI ALFIAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '003. Depok') WHERE full_name = 'DANIEL SOEDIRA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '007. Bekasi') WHERE full_name = 'DEDE';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '045. FX Mall') WHERE full_name = 'DEDE AHDORI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '029. Karawang') WHERE full_name = 'DEDE PUTRA IRAWAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '034. Puri Indah') WHERE full_name = 'DEDY SUPANDI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '007. Bekasi') WHERE full_name = 'DENIS WILLIAMS JAYA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '002. Kemang') WHERE full_name = 'DINO FAIZAL YURID';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '005. Greenville') WHERE full_name = 'DINO IRAWAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '004. Cipete') WHERE full_name = 'DWI PURNOMO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '031. Sawangan') WHERE full_name = 'EDO FIRMANSYAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '055. Gajah Mada') WHERE full_name = 'ELVAN JANGGA PRAMANA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '058. Solo Baru') WHERE full_name = 'ERI FEBRIANSYAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '015. Gading Serpong') WHERE full_name = 'FADLY';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '039. Bandung Mekarwangi') WHERE full_name = 'FAJAR SIDIK';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'FARHAN SENA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '038. Greenlake') WHERE full_name = 'FEBBY TRI PRASTIYO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '021. Kelapa Gading Boulevard') WHERE full_name = 'GEMA AZAN SAPUTRA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '019. Cinere') WHERE full_name = 'HADI APRIYANTO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '035. Ciledug') WHERE full_name = 'HARI JUMADI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '003. Depok') WHERE full_name = 'HARIS SUPRATMAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '040. Bekasi Timur') WHERE full_name = 'HARTONO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '004. Cipete') WHERE full_name = 'HASJMI FERDIAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '014. Sunter') WHERE full_name = 'HENDRA DWI SAPUTRA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '030. Ciputat') WHERE full_name = 'HENDRA MARTONO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '043. Tebet') WHERE full_name = 'HERDI HERMAWAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '021. Kelapa Gading Boulevard') WHERE full_name = 'I PUTU NGURAH DANISWARA D';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '002. Kemang') WHERE full_name = 'IHWAN HASANUDIN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'IQBAL AL BANNA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '010. Bogor') WHERE full_name = 'IRFANSYAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '014. Sunter') WHERE full_name = 'IWAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '028. Taman Palem') WHERE full_name = 'JAMAL PRATAMA PUTRA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '002. Kemang') WHERE full_name = 'JAYADIH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '004. Cipete') WHERE full_name = 'JENDRI NELVI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '024. Grand Wisata') WHERE full_name = 'JUNIANSYAH SYAPUTRA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '011. Kuningan') WHERE full_name = 'KAMALLUDIN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '010. Bogor') WHERE full_name = 'KRISNA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '025. Bogor Baru') WHERE full_name = 'M. FIRMANSYAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '019. Cinere') WHERE full_name = 'MAULANA MALIK';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '057. Cikupa') WHERE full_name = 'MIZWAR ALAMSYAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '044. Depok GDC') WHERE full_name = 'MOHAMMAD HERWIN DWI SAPUTRA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '022. Cikarang') WHERE full_name = 'MUHAMAD FARID';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '067. Agora Mall') WHERE full_name = 'MUHAMAD FATHAN MUBIN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '050. Cibinong') WHERE full_name = 'MUHAMAD HAFIDZ FADILLAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '015. Gading Serpong') WHERE full_name = 'MUHAMAD HUSNI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '036. Jagakarsa') WHERE full_name = 'MUHAMAD KEMAL RIZQULLAH ALGHIFARI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '005. Greenville') WHERE full_name = 'MUHAMAD NAZAR';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'MUHAMAD NOVIAR NURSHOLIHIN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '051. Bintaro Sektor 9') WHERE full_name = 'MUHAMAD VICKRI FATHURROZI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '049. Surabaya Merr') WHERE full_name = 'MUHAMMAD DIAN EKA PAKSI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '013. Bandung Gatsu') WHERE full_name = 'MUHAMMAD ERLANGGA PUTRA PRATAMA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '002. Kemang') WHERE full_name = 'MUHAMMAD FAZA PRATAMA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '014. Sunter') WHERE full_name = 'MUHAMMAD INDRA HASAN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '006. Kelapa Gading MOI') WHERE full_name = 'MUHAMMAD PRAKAS AGAZI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'MUHAMMAD TRI ISMANDANU';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '009. Bintaro') WHERE full_name = 'MUHASABAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '064. Pondok Indah') WHERE full_name = 'MULTAZAM RIZQY RADIANSYAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '052. BSD Rawa Buntu') WHERE full_name = 'NUR HIDAYAT SURYA PRANATA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '004. Cipete') WHERE full_name = 'RESTU DINAR PUJIYANTI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '025. Bogor Baru') WHERE full_name = 'REZA RIZKI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'REZA SUHELMI AN NUR';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'RINA WARSI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '007. Bekasi') WHERE full_name = 'RISKY ANNISA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '012. BSD') WHERE full_name = 'RIVALDI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '001. Pondok Bambu') WHERE full_name = 'ROBI APRIYADI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '001. Pondok Bambu') WHERE full_name = 'SAEFUL MAHENDRA SUCIPTA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '042. Muara Karang') WHERE full_name = 'SAHRUL ICHSANI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '007. Bekasi') WHERE full_name = 'SANDI NAYA KUSUMA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '061. Cirebon') WHERE full_name = 'SARIF HIDAYAT';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '008. PIK') WHERE full_name = 'SAYYIDU SYUHADA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '002. Kemang') WHERE full_name = 'SLAMET';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '053. Alam Sutera') WHERE full_name = 'SOPYAN HARIS';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '048. PIK 2') WHERE full_name = 'SUTRISNA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '065. Kebon Sirih') WHERE full_name = 'TANTO SUTRISNO';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '012. BSD') WHERE full_name = 'TAUFIK HIDAYAT';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '018. Harapan Indah') WHERE full_name = 'TEGUH ARIYANDI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '041. Karawaci') WHERE full_name = 'VIARDICA SAPUTRA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '000. Management') WHERE full_name = 'WASRIKIN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '007. Bekasi') WHERE full_name = 'WIDYA ASTUTI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '020. Surabaya') WHERE full_name = 'YAKUB SYAIFUL ANWAR';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '047. Bogor Tajur') WHERE full_name = 'YUDA WILDAN WIGUNA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '027. Rawamangun') WHERE full_name = 'YUSMAN SYAHRUL';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '017. Bandung Setrasari') WHERE full_name = 'YUSUP APRILIANDI';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '002. Kemang') WHERE full_name = 'ZAINAL ABIDIN';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '043. Tebet') WHERE full_name = 'ZAKARIA';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '003. Depok') WHERE full_name = 'ZULFIAN AFDILLAH';
UPDATE employees SET branch_id = (SELECT id FROM branches WHERE full_name = '046. Kaliurang Jogja') WHERE full_name = 'ZULI ROBIANTO';
