UPDATE inspection_reports SET fc_score = 75, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '030. Ciputat' LIMIT 1) AND inspection_date = '2026-01-06';
UPDATE inspection_reports SET fc_score = 88, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '033. Taman Mini' LIMIT 1) AND inspection_date = '2026-01-07';
UPDATE inspection_reports SET fc_score = 77, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '036. Jagakarsa' LIMIT 1) AND inspection_date = '2026-01-07';
UPDATE inspection_reports SET fc_score = 78, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '027. Rawamangun' LIMIT 1) AND inspection_date = '2026-01-08';
UPDATE inspection_reports SET fc_score = 84, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '032. Cawang' LIMIT 1) AND inspection_date = '2026-01-08';
UPDATE inspection_reports SET fc_score = 83, spv_score = 99 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '024. Grand Wisata' LIMIT 1) AND inspection_date = '2026-01-13';
UPDATE inspection_reports SET fc_score = 81, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '051. Bintaro Sektor 9' LIMIT 1) AND inspection_date = '2026-01-13';
UPDATE inspection_reports SET fc_score = 88, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '026. Tangerang City' LIMIT 1) AND inspection_date = '2026-01-14';
UPDATE inspection_reports SET fc_score = 69, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '044. Depok GDC' LIMIT 1) AND inspection_date = '2026-01-14';
UPDATE inspection_reports SET fc_score = 88, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '008. PIK' LIMIT 1) AND inspection_date = '2026-01-15';
UPDATE inspection_reports SET fc_score = 82, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '053. Alam Sutera' LIMIT 1) AND inspection_date = '2026-01-15';
UPDATE inspection_reports SET fc_score = 84, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '042. Muara Karang' LIMIT 1) AND inspection_date = '2026-01-20';
UPDATE inspection_reports SET fc_score = 90, spv_score = 77 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '028. Taman Palem' LIMIT 1) AND inspection_date = '2026-01-21';
UPDATE inspection_reports SET fc_score = 84, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '011. Kuningan' LIMIT 1) AND inspection_date = '2026-01-27';
UPDATE inspection_reports SET fc_score = 72, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '018. Harapan Indah' LIMIT 1) AND inspection_date = '2026-01-28';
UPDATE inspection_reports SET fc_score = 77, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '041. Karawaci' LIMIT 1) AND inspection_date = '2026-01-28';
UPDATE inspection_reports SET fc_score = 87, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '038. Greenlake' LIMIT 1) AND inspection_date = '2026-01-29';
UPDATE inspection_reports SET fc_score = 75, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '034. Puri Indah' LIMIT 1) AND inspection_date = '2026-02-03';
UPDATE inspection_reports SET fc_score = 84, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '055. Gajah Mada' LIMIT 1) AND inspection_date = '2026-02-03';
UPDATE inspection_reports SET fc_score = 94, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '040. Bekasi Timur' LIMIT 1) AND inspection_date = '2026-02-04';
UPDATE inspection_reports SET fc_score = 94, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '047. Bogor Tajur' LIMIT 1) AND inspection_date = '2026-02-04';
UPDATE inspection_reports SET fc_score = 77, spv_score = 92 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '014. Sunter' LIMIT 1) AND inspection_date = '2026-02-05';
UPDATE inspection_reports SET fc_score = 69, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '029. Karawang' LIMIT 1) AND inspection_date = '2026-02-05';
UPDATE inspection_reports SET fc_score = 85, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '031. Sawangan' LIMIT 1) AND inspection_date = '2026-02-10';
UPDATE inspection_reports SET fc_score = 81, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '048. Pik 2' LIMIT 1) AND inspection_date = '2026-02-10';
UPDATE inspection_reports SET fc_score = 82, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '006. Kelapa Gading MOI' LIMIT 1) AND inspection_date = '2026-02-11';
UPDATE inspection_reports SET fc_score = 82, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '022. Cikarang' LIMIT 1) AND inspection_date = '2026-02-11';
UPDATE inspection_reports SET fc_score = 76, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '015. Gading Serpong' LIMIT 1) AND inspection_date = '2026-02-12';
UPDATE inspection_reports SET fc_score = 67, spv_score = 75 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '035. Ciledug' LIMIT 1) AND inspection_date = '2026-02-12';
UPDATE inspection_reports SET fc_score = 90, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '025. Bogor Baru' LIMIT 1) AND inspection_date = '2026-02-18';
UPDATE inspection_reports SET fc_score = 85, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '019. Cinere' LIMIT 1) AND inspection_date = '2026-02-19';
UPDATE inspection_reports SET fc_score = 85, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '054. Bogor Gunung Batu' LIMIT 1) AND inspection_date = '2026-02-19';
UPDATE inspection_reports SET fc_score = 83, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '045. FX Mall' LIMIT 1) AND inspection_date = '2026-02-24';
UPDATE inspection_reports SET fc_score = 67, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '056. Citra Garden 2' LIMIT 1) AND inspection_date = '2026-02-24';
UPDATE inspection_reports SET fc_score = 78, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '021. Kelapa Gading Boulevard' LIMIT 1) AND inspection_date = '2026-02-25';
UPDATE inspection_reports SET fc_score = 77, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '050. Cibinong' LIMIT 1) AND inspection_date = '2026-02-25';
UPDATE inspection_reports SET fc_score = 68, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '043. Tebet' LIMIT 1) AND inspection_date = '2026-02-26';
UPDATE inspection_reports SET fc_score = 88, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '057. Cikupa' LIMIT 1) AND inspection_date = '2026-02-26';
UPDATE inspection_reports SET fc_score = 66, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '001. Pondok Bambu' LIMIT 1) AND inspection_date = '2026-03-03';
UPDATE inspection_reports SET fc_score = 77, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '052. BSD Rawa Buntu' LIMIT 1) AND inspection_date = '2026-03-03';
UPDATE inspection_reports SET fc_score = 73, spv_score = 80 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '002. Kemang' LIMIT 1) AND inspection_date = '2026-03-04';
UPDATE inspection_reports SET fc_score = 64, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '007. Bekasi' LIMIT 1) AND inspection_date = '2026-03-04';
UPDATE inspection_reports SET fc_score = 84, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '005. Greenville' LIMIT 1) AND inspection_date = '2026-03-05';
UPDATE inspection_reports SET fc_score = 87, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '010. Bogor' LIMIT 1) AND inspection_date = '2026-03-05';
UPDATE inspection_reports SET fc_score = 92, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '037. Bali' LIMIT 1) AND inspection_date = '2026-03-06';
UPDATE inspection_reports SET fc_score = 55, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '004. Cipete' LIMIT 1) AND inspection_date = '2026-03-10';
UPDATE inspection_reports SET fc_score = 90, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '049. Surabaya Merr' LIMIT 1) AND inspection_date = '2026-03-11';
UPDATE inspection_reports SET fc_score = 81, spv_score = 95 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '009. Bintaro' LIMIT 1) AND inspection_date = '2026-03-12';
UPDATE inspection_reports SET fc_score = 83, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '020. Surabaya' LIMIT 1) AND inspection_date = '2026-03-12';
UPDATE inspection_reports SET fc_score = 92, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '023. Semarang' LIMIT 1) AND inspection_date = '2026-03-16';
UPDATE inspection_reports SET fc_score = 61, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '003. Depok' LIMIT 1) AND inspection_date = '2026-03-17';
UPDATE inspection_reports SET fc_score = 69, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '016. Cibubur' LIMIT 1) AND inspection_date = '2026-03-26';
UPDATE inspection_reports SET fc_score = 80, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '033. Taman Mini' LIMIT 1) AND inspection_date = '2026-04-01';
UPDATE inspection_reports SET fc_score = 78, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '032. Cawang' LIMIT 1) AND inspection_date = '2026-04-02';
UPDATE inspection_reports SET fc_score = 71, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '053. Alam Sutera' LIMIT 1) AND inspection_date = '2026-04-08';
UPDATE inspection_reports SET fc_score = 70, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '036. Jagakarsa' LIMIT 1) AND inspection_date = '2026-04-09';
UPDATE inspection_reports SET fc_score = 57, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '024. Grand Wisata' LIMIT 1) AND inspection_date = '2026-04-13';
UPDATE inspection_reports SET fc_score = 58, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '027. Rawamangun' LIMIT 1) AND inspection_date = '2026-04-14';
UPDATE inspection_reports SET fc_score = 75, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '026. Tangerang City' LIMIT 1) AND inspection_date = '2026-04-15';
UPDATE inspection_reports SET fc_score = 82, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '042. Muara Karang' LIMIT 1) AND inspection_date = '2026-04-16';
UPDATE inspection_reports SET fc_score = 67, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '044. Depok GDC' LIMIT 1) AND inspection_date = '2026-04-16';
UPDATE inspection_reports SET fc_score = 71, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '008. PIK' LIMIT 1) AND inspection_date = '2026-04-23';
UPDATE inspection_reports SET fc_score = 85, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '030. Ciputat' LIMIT 1) AND inspection_date = '2026-04-23';
UPDATE inspection_reports SET fc_score = 57, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '028. Taman Palem' LIMIT 1) AND inspection_date = '2026-04-24';
UPDATE inspection_reports SET fc_score = 83, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '055. Gajah Mada' LIMIT 1) AND inspection_date = '2026-04-28';
UPDATE inspection_reports SET fc_score = 76, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '046. Kaliurang Jogja' LIMIT 1) AND inspection_date = '2026-04-30';
UPDATE inspection_reports SET fc_score = 54, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '004. Cipete' LIMIT 1) AND inspection_date = '2026-04-30';
UPDATE inspection_reports SET fc_score = 73, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '038. Greenlake' LIMIT 1) AND inspection_date = '2026-04-30';
UPDATE inspection_reports SET fc_score = 83, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '047. Bogor Tajur' LIMIT 1) AND inspection_date = '2026-04-30';
UPDATE inspection_reports SET fc_score = 58, spv_score = 94 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '035. Ciledug' LIMIT 1) AND inspection_date = '2026-05-06';
UPDATE inspection_reports SET fc_score = 81, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '048. PIK 2' LIMIT 1) AND inspection_date = '2026-05-06';
UPDATE inspection_reports SET fc_score = 70, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '011. Kuningan' LIMIT 1) AND inspection_date = '2026-05-07';
UPDATE inspection_reports SET fc_score = 66, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '005. Greenville' LIMIT 1) AND inspection_date = '2026-05-08';
UPDATE inspection_reports SET fc_score = 51, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '025. Bogor Baru' LIMIT 1) AND inspection_date = '2026-05-12';
UPDATE inspection_reports SET fc_score = 76, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '031. Sawangan' LIMIT 1) AND inspection_date = '2026-05-13';
UPDATE inspection_reports SET fc_score = 50, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '003. Depok' LIMIT 1) AND inspection_date = '2026-05-20';
UPDATE inspection_reports SET fc_score = 68, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '059. Malang Suhat' LIMIT 1) AND inspection_date = '2026-05-25';
UPDATE inspection_reports SET fc_score = 63, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '056. Citra Garden 2' LIMIT 1) AND inspection_date = '2026-05-26';
UPDATE inspection_reports SET fc_score = 71, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '057. Cikupa' LIMIT 1) AND inspection_date = '2026-05-28';
UPDATE inspection_reports SET fc_score = 69, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '021. Kelapa Gading Boulevard' LIMIT 1) AND inspection_date = '2026-06-02';
UPDATE inspection_reports SET fc_score = 69, spv_score = 70 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '043. Tebet' LIMIT 1) AND inspection_date = '2026-06-03';
UPDATE inspection_reports SET fc_score = 50, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '007. Bekasi' LIMIT 1) AND inspection_date = '2026-06-04';
UPDATE inspection_reports SET fc_score = 63, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '060. Palmerah' LIMIT 1) AND inspection_date = '2026-06-05';
UPDATE inspection_reports SET fc_score = 72, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '010. Bogor' LIMIT 1) AND inspection_date = '2026-06-09';
UPDATE inspection_reports SET fc_score = 66, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '016. Cibubur' LIMIT 1) AND inspection_date = '2026-06-10';
UPDATE inspection_reports SET fc_score = 78, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '054. Bogor Gunung Batu' LIMIT 1) AND inspection_date = '2026-06-11';
UPDATE inspection_reports SET fc_score = 64, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '051. Bintaro Sektor 9' LIMIT 1) AND inspection_date = '2026-06-17';
UPDATE inspection_reports SET fc_score = 43, spv_score = 82 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '018. Harapan Indah' LIMIT 1) AND inspection_date = '2026-06-29';
UPDATE inspection_reports SET fc_score = 71, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '050. Cibinong' LIMIT 1) AND inspection_date = '2026-07-06';
UPDATE inspection_reports SET fc_score = 63, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '034. Puri Indah' LIMIT 1) AND inspection_date = '2026-07-09';
UPDATE inspection_reports SET fc_score = 63, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '034. Puri Indah' LIMIT 1) AND inspection_date = '2026-07-09';
UPDATE inspection_reports SET fc_score = 79, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '045. FX Mall' LIMIT 1) AND inspection_date = '2026-07-20';
UPDATE inspection_reports SET fc_score = 81, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '052. BSD Rawa Buntu' LIMIT 1) AND inspection_date = '2026-07-21';
UPDATE inspection_reports SET fc_score = 65, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '019. Cinere' LIMIT 1) AND inspection_date = '2026-07-22';
UPDATE inspection_reports SET fc_score = 82, spv_score = 100 WHERE branch_id = (SELECT id FROM branches WHERE full_name = '031. Sawangan' LIMIT 1) AND inspection_date = '2026-07-24';
